package codegen

import (
	"bytes"
	"fmt"
	"text/template"
)

const (
	decodeBaseType = iota
	encodeBaseType
	decodeDerivedBaseType
	encodeDerivedBaseType
	decodeBaseSliceType
	encodeBaseSliceType
	decodeCustomSliceType
	encodeCustomSliceType
	encodeStructType
	decodeStructType
	encodeSliceStructType
	decodeSliceStructType
)


var fieldTemplate = map[int]string{
	encodeBaseType: `	coder.{{.Method}}({{.ReceiverAlias}}.{{.Field}})`,
	decodeBaseType: `	coder.{{.Method}}(&{{.ReceiverAlias}}.{{.Field}})`,
	decodeDerivedBaseType: `	var {{.TransientVar}} {{.BaseType}}
	coder.{{.Method}}(&{{.TransientVar}})
	{{.ReceiverAlias}}.{{.Field}} = {{.FieldType}}({{.TransientVar}})`,
	encodeDerivedBaseType: `	coder.{{.Method}}({{.BaseType}}({{.ReceiverAlias}}.{{.Field}}))`,
	encodeBaseSliceType: `	coder.{{.Method}}(({{.ReceiverAlias}}.{{.Field}}))`,
	decodeBaseSliceType: `	var {{.TransientVar}} []{{.BaseType}}
	coder.{{.Method}}(&{{.TransientVar}})
	{{.ReceiverAlias}}.{{.Field}} = {{.TransientVar}}`,
	encodeCustomSliceType: `	coder.{{.Method}}(*(*[]{{.BaseType}})(unsafe.Pointer(&{{.ReceiverAlias}}.{{.Field}})))`,
	decodeCustomSliceType: `	var {{.TransientVar}} []{{.BaseType}}
	coder.{{.Method}}(&{{.TransientVar}})
	{{.ReceiverAlias}}.{{.Field}} = *(*{{.FieldType}})(unsafe.Pointer(&{{.TransientVar}}))`,
	encodeStructType: `	coder.{{.Method}}({{if .PointerNeeded}}&{{end}}{{.ReceiverAlias}}.{{.Field}})`,
	decodeStructType: `{{if not .PointerNeeded}}	{{.ReceiverAlias}}.{{.Field}} = &{{.FieldType}}{}
{{end}}	coder.{{.Method}}({{if .PointerNeeded}}&{{end}}{{.ReceiverAlias}}.{{.Field}})`,
	encodeSliceStructType: `	var {{.TransientVar}} = len({{.ReceiverAlias}}.{{.Field}})
	coder.Alloc(int32({{.TransientVar}}))
	for i:=0; i < {{.TransientVar}} ; i++ {
		if err := coder.{{.Method}}({{if .PointerNeeded}}&{{end}}{{.ReceiverAlias}}.{{.Field}}[i]);err !=nil {
			return nil
		}
	}`,
	decodeSliceStructType: `	var {{.TransientVar}} = coder.Alloc()
	{{.ReceiverAlias}}.{{.Field}} = make({{.FieldType}},{{.TransientVar}})
	for i:=0; i < int({{.TransientVar}}) ; i++ {
		tmp := 	{{.FieldType}}{}
		if err := coder.{{.Method}}({{if not .PointerNeeded}}&{{end}}tmp);err != nil {
			return nil
		}
		{{.ReceiverAlias}}.{{.Field}}[i] = {{if not .PointerNeeded}}&{{end}}tmp
	}`,
}

//var m1Size = coder.Alloc()
//m.M1 = make([] SubMessage,m1Size)
//for i:= 0; i <= int(m1Size) ;i++ {
//sm := SubMessage{}
//if err := coder.Coder(&sm);err !=nil {
//return nil
//}
//m.M1[i] = sm
//}

//var m1Size = len(m.M1)
//coder.Alloc(int32(m1Size))
//for i:=0 ; i < m1Size;i++ {
//if err := coder.Coder(&m.M1[i]);err !=nil {
//return nil
//}
//}




const (
	fileCode = iota
	codingStructType
)

var blockTemplate = map[int]string{
	fileCode: `// Code generated by bintly codegen. DO NOT EDIT.\n\n

package {{.Pkg}}

import (
{{.Imports}}
)
{{.Code}}

`,
	codingStructType: `
func ({{.Receiver}}) EncodeBinary(coder *bintly.Writer) error {
{{.EncodingCases}}
	return nil
}
func ({{.Receiver}}) DecodeBinary(coder *bintly.Reader) error {
{{.DecodingCases}}	
	return nil
}
`,
}

func expandTemplate(namespace string, dictionary map[int]string, key int, data interface{}) (string, error) {
	var id = fmt.Sprintf("%v_%v", namespace, key)
	textTemplate, ok := dictionary[key]
	if !ok {
		return "", fmt.Errorf("failed to lookup template for %v.%v", namespace, key)
	}
	temlate, err := template.New(id).Parse(textTemplate)
	if err != nil {
		return "", fmt.Errorf("fiailed to parse template %v %v, due to %v", namespace, key, err)
	}
	writer := new(bytes.Buffer)
	err = temlate.Execute(writer, data)
	return writer.String(), err
}

func expandFieldTemplate(key int, data interface{}) (string, error) {
	return expandTemplate("fieldTemplate", fieldTemplate, key, data)
}

func expandBlockTemplate(key int, data interface{}) (string, error) {
	return expandTemplate("blockTemplate", blockTemplate, key, data)
}
